# Generated by Django 6.0.3 on 2026-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('specialites', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
